# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4c950934db8f74b314e8d89756f1fe803c52fdfe04778c6a5074292ea62a793f9682090f4332f247401fea46ad043f4e3d9810a1720d266cbd1bc8beffb5675

test:
  secret_key_base: ca5be65926bee5ab4c52c2c018d1667492e7afd01af106199fb9d2324c67b778770862df6f17820cd482ed1e95f952d11dc287553b0b4221668703a2f6080d5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
